//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class MyPanel extends JPanel {
    private JTextArea texto_Nombre;
    private JTextArea texto_Dirreccion;
    private JTextArea texto_BomberoResidente;
    private JLabel lable_Nombre;
    private JLabel lable_Dirreccion;
    private JLabel lable_BomberoResidente;
    private JLabel label_SafeZone;
    private JToggleButton boton_inicio;
    private JToggleButton toggelBoton_Alerta;
    private JTextArea jcomp10;
    private JToggleButton ToggleButton_Gravedad;
    private JTextArea jcomp12;

    public MyPanel() {
        //construct components
        texto_Nombre = new JTextArea (5, 5);
        texto_Dirreccion = new JTextArea (5, 5);
        texto_BomberoResidente = new JTextArea (5, 5);
        lable_Nombre = new JLabel ("Ingrese su nombre:");
        lable_Dirreccion = new JLabel ("Ingrese su dirreccion:");
        lable_BomberoResidente = new JLabel ("¿Es usted Bombero?(si/no)");
        label_SafeZone = new JLabel ("SafeZone");
        boton_inicio = new JToggleButton ("Inicio", true);
        toggelBoton_Alerta = new JToggleButton ("Alerta", true);
        jcomp10 = new JTextArea (5, 5);
        ToggleButton_Gravedad = new JToggleButton ("Gravedad", true);
        jcomp12 = new JTextArea (5, 5);

        //adjust size and set layout
        setPreferredSize (new Dimension (944, 574));
        setLayout (null);

        //add components
        add (texto_Nombre);
        add (texto_Dirreccion);
        add (texto_BomberoResidente);
        add (lable_Nombre);
        add (lable_Dirreccion);
        add (lable_BomberoResidente);
        add (label_SafeZone);
        add (boton_inicio);
        add (toggelBoton_Alerta);
        add (jcomp10);
        add (ToggleButton_Gravedad);
        add (jcomp12);

        //set component bounds (only needed by Absolute Positioning)
        texto_Nombre.setBounds (75, 175, 155, 30);
        texto_Dirreccion.setBounds (70, 250, 165, 30);
        texto_BomberoResidente.setBounds (70, 325, 165, 30);
        lable_Nombre.setBounds (75, 145, 155, 25);
        lable_Dirreccion.setBounds (75, 220, 140, 25);
        lable_BomberoResidente.setBounds (70, 290, 180, 30);
        label_SafeZone.setBounds (340, 30, 124, 50);
        boton_inicio.setBounds (90, 85, 100, 25);
        toggelBoton_Alerta.setBounds (570, 90, 100, 25);
        jcomp10.setBounds (495, 130, 360, 165);
        ToggleButton_Gravedad.setBounds (495, 330, 100, 25);
        jcomp12.setBounds (495, 365, 355, 60);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new MyPanel());
        frame.pack();
        frame.setVisible (true);
    }
}
